--------------------------------------------------------
--  文件已创建 - 星期三-五月-24-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "BBS"."ACCOUNT" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"USERID" NUMBER(10,0), 
	"ROLE" NUMBER(3,0) DEFAULT 10, 
	"LATEST_LOGIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
REM INSERTING into BBS.ACCOUNT
SET DEFINE OFF;
Insert into BBS.ACCOUNT (USERNAME,PASSWORD,USERID,ROLE,LATEST_LOGIN) values ('lyk','lyk',3,10,null);
Insert into BBS.ACCOUNT (USERNAME,PASSWORD,USERID,ROLE,LATEST_LOGIN) values ('test2','test2',2,10,null);
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BBS"."ACCOUNT_PK" ON "BBS"."ACCOUNT" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "BBS"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS"  ENABLE;
 
  ALTER TABLE "BBS"."ACCOUNT" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ACCOUNT" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ACCOUNT" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "BBS"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "BBS"."BBS_USER" ("ID") ON DELETE CASCADE ENABLE;
