--------------------------------------------------------
--  文件已创建 - 星期一-五月-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ACCOUNT" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"USERID" NUMBER(10,0), 
	"ROLE" NUMBER(3,0) DEFAULT 10, 
	"LATEST_LOGIN" DATE, 
	"CREATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
REM INSERTING into ACCOUNT
SET DEFINE OFF;
Insert into ACCOUNT (USERNAME,PASSWORD,USERID,ROLE,LATEST_LOGIN,CREATE_TIME) values ('13262797296','chen2668',100000040,10,to_date('2017-05-29 18:23:29','YYYY-MM-DD HH24:MI:SS'),to_date('2017-05-29 18:22:24','YYYY-MM-DD HH24:MI:SS'));
Insert into ACCOUNT (USERNAME,PASSWORD,USERID,ROLE,LATEST_LOGIN,CREATE_TIME) values ('lyk','lyk',3,10,to_date('2017-05-29 19:05:23','YYYY-MM-DD HH24:MI:SS'),to_date('2017-05-01 06:33:14','YYYY-MM-DD HH24:MI:SS'));
Insert into ACCOUNT (USERNAME,PASSWORD,USERID,ROLE,LATEST_LOGIN,CREATE_TIME) values ('test2','test2',2,10,to_date('2017-05-29 18:40:53','YYYY-MM-DD HH24:MI:SS'),to_date('2017-05-01 06:33:18','YYYY-MM-DD HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_PK" ON "ACCOUNT" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS"  ENABLE;
 
  ALTER TABLE "ACCOUNT" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT" MODIFY ("USERID" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "BBS_USER" ("ID") ON DELETE CASCADE ENABLE;
