--------------------------------------------------------
--  文件已创建 - 星期二-五月-23-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANSWER
--------------------------------------------------------

  CREATE TABLE "BBS"."ANSWER" 
   (	"ID" NUMBER(14,0), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"CREATE_BY" NUMBER(10,0), 
	"CREATE_TIME" DATE, 
	"QUESTION_ID" NUMBER(12,0), 
	"HELPFUL" NUMBER(8,0) DEFAULT 0, 
	"NAME" VARCHAR2(20 BYTE), 
	"IS_ACCLAIMED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "BBS"."ANSWER"."ID" IS '答案主键';
 
   COMMENT ON COLUMN "BBS"."ANSWER"."CONTENT" IS '内容';
 
   COMMENT ON COLUMN "BBS"."ANSWER"."CREATE_BY" IS '创建人';
 
   COMMENT ON COLUMN "BBS"."ANSWER"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "BBS"."ANSWER"."QUESTION_ID" IS '问题外键';
 
   COMMENT ON COLUMN "BBS"."ANSWER"."HELPFUL" IS '其他用户意见';
 
   COMMENT ON COLUMN "BBS"."ANSWER"."NAME" IS '编辑人';
 
   COMMENT ON COLUMN "BBS"."ANSWER"."IS_ACCLAIMED" IS '好评';
REM INSERTING into BBS.ANSWER
SET DEFINE OFF;
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (30,'<p>gg</p>',2,to_date('2017-05-19 11:46:55','YYYY-MM-DD HH24:MI:SS'),35,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (132,'<p>ggg&nbsp;</p>',3,to_date('2017-05-21 19:26:54','YYYY-MM-DD HH24:MI:SS'),105,5,'lyk',1);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (34,'<p>测试</p>',2,to_date('2017-05-19 12:09:44','YYYY-MM-DD HH24:MI:SS'),38,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (135,'<p>gg</p>',3,to_date('2017-05-21 19:54:08','YYYY-MM-DD HH24:MI:SS'),34,0,'lyk',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (65,'<p>啥？</p>',2,to_date('2017-05-19 15:19:55','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (11,'<p>测试对比</p>',2,to_date('2017-05-17 01:07:27','YYYY-MM-DD HH24:MI:SS'),18,0,'test',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (37,'<p>test</p>',2,to_date('2017-05-19 12:28:48','YYYY-MM-DD HH24:MI:SS'),41,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (112,'<p>事实上</p>',3,to_date('2017-05-19 22:48:07','YYYY-MM-DD HH24:MI:SS'),86,0,'lyk',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (110,'<p>参与度</p>',3,to_date('2017-05-19 22:46:03','YYYY-MM-DD HH24:MI:SS'),84,0,'lyk',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (42,'<p>啥</p>',2,to_date('2017-05-19 14:16:39','YYYY-MM-DD HH24:MI:SS'),35,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (44,'<p>测试</p>',2,to_date('2017-05-19 14:27:12','YYYY-MM-DD HH24:MI:SS'),35,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (45,'<p>踩踩踩</p>',2,to_date('2017-05-19 14:29:10','YYYY-MM-DD HH24:MI:SS'),33,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (46,'<p>ss</p>',2,to_date('2017-05-19 14:32:05','YYYY-MM-DD HH24:MI:SS'),35,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (47,'<p>?????</p>',2,to_date('2017-05-19 14:33:00','YYYY-MM-DD HH24:MI:SS'),35,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (48,'<p>?</p>',2,to_date('2017-05-19 14:36:23','YYYY-MM-DD HH24:MI:SS'),35,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (49,'<p>test</p>',2,to_date('2017-05-19 14:38:48','YYYY-MM-DD HH24:MI:SS'),18,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (50,'<p><a href="https://my.oschina.net/sucre/blog/377940?p=1">https://my.oschina.net/sucre/blog/377940?p=1</a></p>',2,to_date('2017-05-19 14:44:41','YYYY-MM-DD HH24:MI:SS'),18,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (51,'<p>愤愤然</p>',2,to_date('2017-05-19 14:46:01','YYYY-MM-DD HH24:MI:SS'),18,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (52,'<p>更改</p>',2,to_date('2017-05-19 14:52:43','YYYY-MM-DD HH24:MI:SS'),18,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (53,'<p>更哦哦哦</p>',2,to_date('2017-05-19 14:53:25','YYYY-MM-DD HH24:MI:SS'),18,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (54,'<p>？</p>',2,to_date('2017-05-19 14:53:33','YYYY-MM-DD HH24:MI:SS'),18,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (55,'<p>？</p>',2,to_date('2017-05-19 14:57:52','YYYY-MM-DD HH24:MI:SS'),18,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (56,'<p>测试</p>',2,to_date('2017-05-19 14:58:43','YYYY-MM-DD HH24:MI:SS'),37,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (57,'<p>啥</p>',2,to_date('2017-05-19 15:03:17','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (58,'<p>有用没</p>',2,to_date('2017-05-19 15:09:37','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (59,'<p>试试</p>',2,to_date('2017-05-19 15:11:18','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (60,'<p>试试hi</p>',2,to_date('2017-05-19 15:12:52','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (61,'<p>测试</p>',2,to_date('2017-05-19 15:13:52','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (62,'<p>谔谔</p>',2,to_date('2017-05-19 15:15:02','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (64,'<p>再来</p>',2,to_date('2017-05-19 15:17:20','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (133,'<p>fff</p>',3,to_date('2017-05-21 19:43:10','YYYY-MM-DD HH24:MI:SS'),106,5,'lyk',1);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (28,'<p>测试答案昵称字段</p>',2,to_date('2017-05-19 10:24:50','YYYY-MM-DD HH24:MI:SS'),34,1,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (29,'<p>测试同一id提交多次答案</p>',2,to_date('2017-05-19 10:27:13','YYYY-MM-DD HH24:MI:SS'),34,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (33,'<p>测试</p>',2,to_date('2017-05-19 12:09:22','YYYY-MM-DD HH24:MI:SS'),37,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (32,'<p>测试</p>',2,to_date('2017-05-19 12:08:17','YYYY-MM-DD HH24:MI:SS'),37,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (41,'<p>为毛</p>',2,to_date('2017-05-19 14:14:52','YYYY-MM-DD HH24:MI:SS'),35,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (43,'<p>日日日</p>',2,to_date('2017-05-19 14:19:41','YYYY-MM-DD HH24:MI:SS'),35,0,'test2',0);
Insert into BBS.ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (63,'<p>唉</p>',2,to_date('2017-05-19 15:15:55','YYYY-MM-DD HH24:MI:SS'),27,0,'test2',0);
--------------------------------------------------------
--  DDL for Index ANSWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BBS"."ANSWER_PK" ON "BBS"."ANSWER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ANSWER
--------------------------------------------------------

  ALTER TABLE "BBS"."ANSWER" ADD CONSTRAINT "ANSWER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BBS"."ANSWER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ANSWER" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ANSWER" MODIFY ("CREATE_BY" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ANSWER" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ANSWER" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ANSWER" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TRIGGER_ASWER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BBS"."TRIGGER_ASWER" 
BEFORE INSERT ON ANSWER 
FOR EACH ROW 
  WHEN (new.id is null) BEGIN
  select sequence_answer.nextval into :new.id from dual;
END;
/
ALTER TRIGGER "BBS"."TRIGGER_ASWER" ENABLE;
