--------------------------------------------------------
--  文件已创建 - 星期二-五月-23-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANSWER_HELP
--------------------------------------------------------

  CREATE TABLE "BBS"."ANSWER_HELP" 
   (	"ANSWER_ID" NUMBER(14,0), 
	"USER_ID" NUMBER(10,0), 
	"CREATE_TIME" DATE, 
	"IS_HELPFUL" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "BBS"."ANSWER_HELP"."ANSWER_ID" IS '答案外键';
 
   COMMENT ON COLUMN "BBS"."ANSWER_HELP"."USER_ID" IS '用户外键';
 
   COMMENT ON COLUMN "BBS"."ANSWER_HELP"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "BBS"."ANSWER_HELP"."IS_HELPFUL" IS '是否有用';
REM INSERTING into BBS.ANSWER_HELP
SET DEFINE OFF;
Insert into BBS.ANSWER_HELP (ANSWER_ID,USER_ID,CREATE_TIME,IS_HELPFUL) values (132,3,to_date('2017-05-21 19:26:58','YYYY-MM-DD HH24:MI:SS'),1);
Insert into BBS.ANSWER_HELP (ANSWER_ID,USER_ID,CREATE_TIME,IS_HELPFUL) values (133,3,to_date('2017-05-21 19:43:44','YYYY-MM-DD HH24:MI:SS'),1);
Insert into BBS.ANSWER_HELP (ANSWER_ID,USER_ID,CREATE_TIME,IS_HELPFUL) values (28,2,to_date('2017-05-19 10:25:03','YYYY-MM-DD HH24:MI:SS'),1);
--------------------------------------------------------
--  DDL for Index HELP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BBS"."HELP_PK" ON "BBS"."ANSWER_HELP" ("ANSWER_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ANSWER_HELP
--------------------------------------------------------

  ALTER TABLE "BBS"."ANSWER_HELP" ADD CONSTRAINT "HELP_PK" PRIMARY KEY ("ANSWER_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BBS"."ANSWER_HELP" MODIFY ("ANSWER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ANSWER_HELP" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ANSWER_HELP" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."ANSWER_HELP" MODIFY ("IS_HELPFUL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANSWER_HELP
--------------------------------------------------------

  ALTER TABLE "BBS"."ANSWER_HELP" ADD CONSTRAINT "ANSWER_HELP_FK1" FOREIGN KEY ("ANSWER_ID")
	  REFERENCES "BBS"."ANSWER" ("ID") ON DELETE CASCADE ENABLE;
