--------------------------------------------------------
--  文件已创建 - 星期一-五月-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANSWER_HELP
--------------------------------------------------------

  CREATE TABLE "ANSWER_HELP" 
   (	"ANSWER_ID" NUMBER(14,0), 
	"USER_ID" NUMBER(10,0), 
	"CREATE_TIME" DATE, 
	"IS_HELPFUL" NUMBER(2,0), 
	"CREATE_BY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "ANSWER_HELP"."ANSWER_ID" IS '答案外键';
 
   COMMENT ON COLUMN "ANSWER_HELP"."USER_ID" IS '操作人';
 
   COMMENT ON COLUMN "ANSWER_HELP"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "ANSWER_HELP"."IS_HELPFUL" IS '是否有用';
 
   COMMENT ON COLUMN "ANSWER_HELP"."CREATE_BY" IS '答案创建人';
REM INSERTING into ANSWER_HELP
SET DEFINE OFF;
Insert into ANSWER_HELP (ANSWER_ID,USER_ID,CREATE_TIME,IS_HELPFUL,CREATE_BY) values (133,2,to_date('2017-05-29 10:49:14','YYYY-MM-DD HH24:MI:SS'),1,3);
--------------------------------------------------------
--  DDL for Index HELP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HELP_PK" ON "ANSWER_HELP" ("ANSWER_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ANSWER_HELP
--------------------------------------------------------

  ALTER TABLE "ANSWER_HELP" ADD CONSTRAINT "HELP_PK" PRIMARY KEY ("ANSWER_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ANSWER_HELP" MODIFY ("ANSWER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER_HELP" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER_HELP" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER_HELP" MODIFY ("IS_HELPFUL" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER_HELP" MODIFY ("CREATE_BY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANSWER_HELP
--------------------------------------------------------

  ALTER TABLE "ANSWER_HELP" ADD CONSTRAINT "ANSWER_HELP_FK1" FOREIGN KEY ("ANSWER_ID")
	  REFERENCES "ANSWER" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "ANSWER_HELP" ADD CONSTRAINT "ANSWER_HELP_FK2" FOREIGN KEY ("CREATE_BY")
	  REFERENCES "BBS_USER" ("ID") ON DELETE CASCADE ENABLE;
