--------------------------------------------------------
--  文件已创建 - 星期一-五月-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANSWER
--------------------------------------------------------

  CREATE TABLE "ANSWER" 
   (	"ID" NUMBER(14,0), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"CREATE_BY" NUMBER(10,0), 
	"CREATE_TIME" DATE, 
	"QUESTION_ID" NUMBER(12,0), 
	"HELPFUL" NUMBER(8,0) DEFAULT 0, 
	"NAME" VARCHAR2(20 BYTE), 
	"IS_ACCLAIMED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "ANSWER"."ID" IS '答案主键';
 
   COMMENT ON COLUMN "ANSWER"."CONTENT" IS '内容';
 
   COMMENT ON COLUMN "ANSWER"."CREATE_BY" IS '创建人';
 
   COMMENT ON COLUMN "ANSWER"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "ANSWER"."QUESTION_ID" IS '问题外键';
 
   COMMENT ON COLUMN "ANSWER"."HELPFUL" IS '其他用户意见';
 
   COMMENT ON COLUMN "ANSWER"."NAME" IS '编辑人';
 
   COMMENT ON COLUMN "ANSWER"."IS_ACCLAIMED" IS '好评';
REM INSERTING into ANSWER
SET DEFINE OFF;
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (132,'<p>ggg ;</p>',3,to_date('2017-05-21 19:26:54','YYYY-MM-DD HH24:MI:SS'),105,5,'lyk',1);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (135,'<p>gg</p>',3,to_date('2017-05-21 19:54:08','YYYY-MM-DD HH24:MI:SS'),34,0,'lyk',0);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (112,'<p>事实上</p>',3,to_date('2017-05-19 22:48:07','YYYY-MM-DD HH24:MI:SS'),86,0,'lyk',0);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (45,'<p>踩踩踩</p>',2,to_date('2017-05-19 14:29:10','YYYY-MM-DD HH24:MI:SS'),33,0,'test2',0);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (56,'<p>测试</p>',2,to_date('2017-05-19 14:58:43','YYYY-MM-DD HH24:MI:SS'),37,0,'test2',0);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (133,'<p>fff</p>',3,to_date('2017-05-21 19:43:10','YYYY-MM-DD HH24:MI:SS'),106,5,'lyk',1);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (28,'<p>测试答案昵称字段</p>',2,to_date('2017-05-19 10:24:50','YYYY-MM-DD HH24:MI:SS'),34,1,'test2',0);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (29,'<p>测试同一id提交多次答案</p>',2,to_date('2017-05-19 10:27:13','YYYY-MM-DD HH24:MI:SS'),34,0,'test2',0);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (33,'<p>测试</p>',2,to_date('2017-05-19 12:09:22','YYYY-MM-DD HH24:MI:SS'),37,0,'test2',0);
Insert into ANSWER (ID,CONTENT,CREATE_BY,CREATE_TIME,QUESTION_ID,HELPFUL,NAME,IS_ACCLAIMED) values (32,'<p>测试</p>',2,to_date('2017-05-19 12:08:17','YYYY-MM-DD HH24:MI:SS'),37,0,'test2',0);
--------------------------------------------------------
--  DDL for Index ANSWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANSWER_PK" ON "ANSWER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ANSWER
--------------------------------------------------------

  ALTER TABLE "ANSWER" ADD CONSTRAINT "ANSWER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ANSWER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER" MODIFY ("CREATE_BY" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ANSWER" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANSWER
--------------------------------------------------------

  ALTER TABLE "ANSWER" ADD CONSTRAINT "ANSWER_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "QUESTION" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_ASWER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRIGGER_ASWER" 
BEFORE INSERT ON ANSWER 
FOR EACH ROW 
  WHEN (new.id is null) BEGIN
  select sequence_answer.nextval into :new.id from dual;
END;
/
ALTER TRIGGER "TRIGGER_ASWER" ENABLE;
