--------------------------------------------------------
--  文件已创建 - 星期二-五月-23-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BBS_USER
--------------------------------------------------------

  CREATE TABLE "BBS"."BBS_USER" 
   (	"ID" NUMBER(10,0), 
	"NICKNAME" VARCHAR2(14 BYTE), 
	"SEX" NUMBER(1,0), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"BIRTHDAY" DATE, 
	"Q_MAJOR" VARCHAR2(1800 BYTE) DEFAULT '{}', 
	"Q_PARTICIPATE" VARCHAR2(1800 BYTE) DEFAULT '{}', 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"AQ_CNT" NUMBER(8,0) DEFAULT 0, 
	"GA_CNT" NUMBER(8,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "BBS"."BBS_USER"."NICKNAME" IS '昵称';
 
   COMMENT ON COLUMN "BBS"."BBS_USER"."SEX" IS '性别';
 
   COMMENT ON COLUMN "BBS"."BBS_USER"."TELEPHONE" IS '电话';
 
   COMMENT ON COLUMN "BBS"."BBS_USER"."BIRTHDAY" IS '生日';
 
   COMMENT ON COLUMN "BBS"."BBS_USER"."Q_MAJOR" IS '擅长问题';
 
   COMMENT ON COLUMN "BBS"."BBS_USER"."Q_PARTICIPATE" IS '参与问题';
 
   COMMENT ON COLUMN "BBS"."BBS_USER"."ADDRESS" IS '地址';
 
   COMMENT ON COLUMN "BBS"."BBS_USER"."AQ_CNT" IS '回答过的问题数量';
 
   COMMENT ON COLUMN "BBS"."BBS_USER"."GA_CNT" IS '好评的回答数量';
REM INSERTING into BBS.BBS_USER
SET DEFINE OFF;
Insert into BBS.BBS_USER (ID,NICKNAME,SEX,TELEPHONE,BIRTHDAY,Q_MAJOR,Q_PARTICIPATE,ADDRESS,AQ_CNT,GA_CNT) values (3,'lyk',1,null,null,'[{"index":10100,"percent":0.667},{"index":30000,"percent":0.333}]','[{"index":20100,"percent":0.333},{"index":25050,"percent":0.333},{"index":10100,"percent":0.333},{"index":10500,"percent":0.167},{"index":30100,"percent":0.167},{"index":15200,"percent":0.167},{"index":15150,"percent":0.167},{"index":30000,"percent":0.167},{"index":15100,"percent":0.167}]',null,6,0);
Insert into BBS.BBS_USER (ID,NICKNAME,SEX,TELEPHONE,BIRTHDAY,Q_MAJOR,Q_PARTICIPATE,ADDRESS,AQ_CNT,GA_CNT) values (1,'test1',0,null,null,'{}','{}',null,0,0);
Insert into BBS.BBS_USER (ID,NICKNAME,SEX,TELEPHONE,BIRTHDAY,Q_MAJOR,Q_PARTICIPATE,ADDRESS,AQ_CNT,GA_CNT) values (2,'test2',1,null,null,'{}','{"10350":0.0}',null,18,0);
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BBS"."TABLE1_PK" ON "BBS"."BBS_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BBS_USER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BBS"."BBS_USER_UK1" ON "BBS"."BBS_USER" ("TELEPHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BBS_USER
--------------------------------------------------------

  ALTER TABLE "BBS"."BBS_USER" ADD CONSTRAINT "BBS_USER_UK1" UNIQUE ("TELEPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BBS"."BBS_USER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "BBS"."BBS_USER" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
