--------------------------------------------------------
--  文件已创建 - 星期二-六月-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BROWSE
--------------------------------------------------------

  CREATE TABLE "BROWSE" 
   (	"BROWSE_ID" NUMBER(14,0), 
	"USER_ID" NUMBER(14,0), 
	"BROWSE_TIME" DATE, 
	"BROWSE_COUNT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
 

   COMMENT ON COLUMN "BROWSE"."BROWSE_ID" IS '浏览帖子外键';
 
   COMMENT ON COLUMN "BROWSE"."USER_ID" IS '用户外键';
 
   COMMENT ON COLUMN "BROWSE"."BROWSE_TIME" IS '最后一次浏览时间';
 
   COMMENT ON COLUMN "BROWSE"."BROWSE_COUNT" IS '浏览次数';
REM INSERTING into BROWSE
SET DEFINE OFF;
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (10,3,to_date('05-6月 -17','DD-MON-RR'),4);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (2,2,to_date('30-5月 -17','DD-MON-RR'),2);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (3,2,to_date('30-5月 -17','DD-MON-RR'),5);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (4,2,to_date('30-5月 -17','DD-MON-RR'),2);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (5,2,to_date('30-5月 -17','DD-MON-RR'),1);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (3,3,to_date('05-6月 -17','DD-MON-RR'),8);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (4,3,to_date('05-6月 -17','DD-MON-RR'),3);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (2,3,to_date('05-6月 -17','DD-MON-RR'),1);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (23,3,to_date('05-6月 -17','DD-MON-RR'),2);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (23,2,to_date('05-6月 -17','DD-MON-RR'),4);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (10,2,to_date('30-5月 -17','DD-MON-RR'),2);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (11,3,to_date('05-6月 -17','DD-MON-RR'),13);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (6,3,to_date('05-6月 -17','DD-MON-RR'),5);
Insert into BROWSE (BROWSE_ID,USER_ID,BROWSE_TIME,BROWSE_COUNT) values (5,3,to_date('05-6月 -17','DD-MON-RR'),4);
--------------------------------------------------------
--  DDL for Index BROWSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROWSE_PK" ON "BROWSE" ("BROWSE_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
--------------------------------------------------------
--  Constraints for Table BROWSE
--------------------------------------------------------

  ALTER TABLE "BROWSE" ADD CONSTRAINT "BROWSE_PK" PRIMARY KEY ("BROWSE_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS"  ENABLE;
 
  ALTER TABLE "BROWSE" MODIFY ("BROWSE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BROWSE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BROWSE" MODIFY ("BROWSE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "BROWSE" MODIFY ("BROWSE_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BROWSE
--------------------------------------------------------

  ALTER TABLE "BROWSE" ADD CONSTRAINT "BROWSE_FK1" FOREIGN KEY ("BROWSE_ID")
	  REFERENCES "POST" ("ID") ENABLE;
 
  ALTER TABLE "BROWSE" ADD CONSTRAINT "BROWSE_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "BBS_USER" ("ID") ENABLE;
