--------------------------------------------------------
--  文件已创建 - 星期四-五月-25-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "POST" 
   (	"ID" NUMBER(10,0), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"POST_TIME" DATE, 
	"TAGS" VARCHAR2(100 BYTE), 
	"VIEWS" NUMBER(10,0) DEFAULT 0, 
	"REPLYS" NUMBER(10,0) DEFAULT 0, 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"FLOOR" NUMBER(10,0) DEFAULT 1, 
	"POST_USER" NUMBER(10,0), 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
 

   COMMENT ON COLUMN "POST"."ID" IS '帖子主键';
 
   COMMENT ON COLUMN "POST"."CONTENT" IS '内容';
 
   COMMENT ON COLUMN "POST"."TITLE" IS '标题';
 
   COMMENT ON COLUMN "POST"."POST_TIME" IS '发布时间';
 
   COMMENT ON COLUMN "POST"."TAGS" IS '标签';
 
   COMMENT ON COLUMN "POST"."VIEWS" IS '访问量';
 
   COMMENT ON COLUMN "POST"."REPLYS" IS '回复量';
 
   COMMENT ON COLUMN "POST"."STATUS" IS '帖子状态';
 
   COMMENT ON COLUMN "POST"."FLOOR" IS '当前楼层';
 
   COMMENT ON COLUMN "POST"."POST_USER" IS '发布者';
 
   COMMENT ON COLUMN "POST"."UPDATE_TIME" IS '最后更新时间';
REM INSERTING into POST
SET DEFINE OFF;
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME) values (1,'<p>改改改</p>','烦烦烦',to_date('25-5月 -17','DD-MON-RR'),'[]',0,0,0,1,3,to_date('25-5月 -17','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POST_PK" ON "POST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "POST" ADD CONSTRAINT "POST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS"  ENABLE;
 
  ALTER TABLE "POST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("POST_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("POST_USER" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TRIGGER_POST
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRIGGER_POST" 
BEFORE INSERT ON POST 
FOR EACH ROW 
 WHEN (new.id is null) BEGIN
  select sequence_post.nextval into :new.id from dual;
END;
/
ALTER TRIGGER "TRIGGER_POST" ENABLE;
