--------------------------------------------------------
--  文件已创建 - 星期二-六月-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "POST" 
   (	"ID" NUMBER(10,0), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"POST_TIME" DATE, 
	"TAGS" VARCHAR2(100 BYTE), 
	"VIEWS" NUMBER(10,0) DEFAULT 0, 
	"REPLYS" NUMBER(10,0) DEFAULT 0, 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"FLOOR" NUMBER(10,0) DEFAULT 1, 
	"POST_USER" NUMBER(10,0), 
	"UPDATE_TIME" DATE, 
	"REWARDS" NUMBER(3,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"ACCEPT_ID" NUMBER(14,0) DEFAULT 0, 
	"REMINDER" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
 

   COMMENT ON COLUMN "POST"."ID" IS '帖子主键';
 
   COMMENT ON COLUMN "POST"."CONTENT" IS '内容';
 
   COMMENT ON COLUMN "POST"."TITLE" IS '标题';
 
   COMMENT ON COLUMN "POST"."POST_TIME" IS '发布时间';
 
   COMMENT ON COLUMN "POST"."TAGS" IS '标签';
 
   COMMENT ON COLUMN "POST"."VIEWS" IS '访问量';
 
   COMMENT ON COLUMN "POST"."REPLYS" IS '回复量';
 
   COMMENT ON COLUMN "POST"."STATUS" IS '帖子状态';
 
   COMMENT ON COLUMN "POST"."FLOOR" IS '当前楼层';
 
   COMMENT ON COLUMN "POST"."POST_USER" IS '发布者';
 
   COMMENT ON COLUMN "POST"."UPDATE_TIME" IS '最后更新时间';
 
   COMMENT ON COLUMN "POST"."REWARDS" IS '悬赏分';
 
   COMMENT ON COLUMN "POST"."NAME" IS '发布人姓名';
 
   COMMENT ON COLUMN "POST"."ACCEPT_ID" IS '采纳回复ID';
REM INSERTING into POST
SET DEFINE OFF;
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (2,'<p>test</p>','test',to_date('26-5月 -17','DD-MON-RR'),'["10500","15100"]',182,1,0,2,3,to_date('29-5月 -17','DD-MON-RR'),25,'lyk',0,1);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (6,'<p>11111</p>','测试发帖得分',to_date('28-5月 -17','DD-MON-RR'),'["10450"]',52,2,0,3,3,to_date('29-5月 -17','DD-MON-RR'),10,'lyk111',0,2);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (22,'<p>11111111111111</p>','测试',to_date('05-6月 -17','DD-MON-RR'),'["15150"]',0,0,0,1,3,to_date('05-6月 -17','DD-MON-RR'),50,'lyk111',0,0);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (23,'<p>11111111111111</p>','测试',to_date('05-6月 -17','DD-MON-RR'),'["15150"]',9,2,0,3,3,to_date('05-6月 -17','DD-MON-RR'),50,'lyk111',0,1);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (3,'<p>dsgsdgsdgggggggggggggggggggggggggggggggggggg</p>','111111',to_date('26-5月 -17','DD-MON-RR'),'[]',282,8,0,9,3,to_date('29-5月 -17','DD-MON-RR'),50,'lyk111',32,8);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (10,'<p>111</p>','111',to_date('29-5月 -17','DD-MON-RR'),'["10450"]',35,0,1,1,2,to_date('29-5月 -17','DD-MON-RR'),50,'test2',0,0);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (21,'<p>11111111111111</p>','测试',to_date('05-6月 -17','DD-MON-RR'),'["15150"]',0,0,0,1,3,to_date('05-6月 -17','DD-MON-RR'),50,'lyk111',0,0);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (4,'<p>测试发帖得分</p>','测试发帖得分',to_date('28-5月 -17','DD-MON-RR'),'["15100"]',11,1,0,2,3,to_date('05-6月 -17','DD-MON-RR'),11,'lyk111',0,1);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (5,'<p>111</p>','测试发帖得分',to_date('28-5月 -17','DD-MON-RR'),'["10400"]',11,1,0,2,3,to_date('05-6月 -17','DD-MON-RR'),25,'lyk111',0,1);
Insert into POST (ID,CONTENT,TITLE,POST_TIME,TAGS,VIEWS,REPLYS,STATUS,FLOOR,POST_USER,UPDATE_TIME,REWARDS,NAME,ACCEPT_ID,REMINDER) values (11,'<p>52525252525</p>','222',to_date('29-5月 -17','DD-MON-RR'),'["10450"]',20,1,1,2,3,to_date('05-6月 -17','DD-MON-RR'),50,'lyk111',0,0);
--------------------------------------------------------
--  DDL for Index POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POST_PK" ON "POST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS" ;
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "POST" ADD CONSTRAINT "POST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BBSTS"  ENABLE;
 
  ALTER TABLE "POST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("POST_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("POST_USER" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("REWARDS" NOT NULL ENABLE);
 
  ALTER TABLE "POST" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TRIGGER_POST
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRIGGER_POST" 
BEFORE INSERT ON POST 
FOR EACH ROW 
 WHEN (new.id is null) BEGIN
  select sequence_post.nextval into :new.id from dual;
END;
/
ALTER TRIGGER "TRIGGER_POST" ENABLE;
